### PR TITLE
Fix bug in directory action

### PR DESCRIPTION
**Pull request by tjgurwara99**
This is a patch to issue https://github.com/TheAlgorithms/scripts/issues/27

To test this I need to whip up something

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
LGTM! Thanks. 🚀
In case it doesn't work, we can revert the changes. 🙂

**Comment by Panquesito7** [comment]
Looks like the issue's still there: https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/5439226228/jobs/9962705411#step:3:51

**Comment by tjgurwara99** [comment]
Ok, I'll take a look soon

**Comment by Panquesito7** [comment]
Ping.

**Pull request merged**
